<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TGC</RootNamespace>
    <AssemblyName>TGC-NG</AssemblyName>
    <Version>3.0.1</Version>
    <AssemblyVersion>3.0.1.0</AssemblyVersion>
    <FileVersion>3.0.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WTT-ServerCommonLib" Version="3.0.6" />
  </ItemGroup>
</Project>

