<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><LangVersion>10.0</LangVersion><Nullable>disable</Nullable><ImplicitUsings>disable</ImplicitUsings><AssemblyName>BAndHB.Integration.BuildInput</AssemblyName><Version>0.3.0</Version></PropertyGroup></Project>
