<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><AssemblyName>0Harmony</AssemblyName><ImplicitUsings>enable</ImplicitUsings><Nullable>disable</Nullable></PropertyGroup><ItemGroup><Compile Include="../Runtime/IntegratedBeltAccess.cs" Link="IntegratedBeltAccess.cs" /></ItemGroup></Project>
