using System;
using System.Collections;
using System.Linq;
using System.Reflection;
using BepInEx;
using BepInEx.Configuration;
using UnityEngine;

namespace SPTPopCounter
{
 [BepInPlugin("com.admiralam.spt.tacticalhud","SPT Tactical HUD","1.4.0")]
 public sealed class Plugin:BaseUnityPlugin
 {
  ConfigEntry<bool> workAlways,editMode,popEnabled,statusEnabled,statusOutside,killEnabled,showVersion;
  ConfigEntry<KeyboardShortcut> toggleKey; ConfigEntry<int> popSize,statusSize,killSize; ConfigEntry<string> killMode;
  ConfigEntry<float> popOpacity,statusOpacity,killOpacity,popX,popY,statusX,statusY,killX,killY;
  ConfigEntry<Color> pmcColor,scavColor,bossColor,reinforcedColor,statusColor,weightOk,weightHeavy,weightCritical,killNeutral;
  float nextRefresh,nextVersionScan; int mode,pmc,scav,boss,reinforced; bool inRaid; float hydration,energy,weight,maxWeight;
  GUIStyle text,shadow,edit; Type worldType,singletonType; PropertyInfo singletonInstance; MemberInfo playersMember; Vector2 dragOffset; int dragCluster;

  void Awake(){
   workAlways=Config.Bind("General","Work Always",false,"Debug override. Raid-only clusters may be previewed outside a raid.");
   toggleKey=Config.Bind("General","Toggle Key",new KeyboardShortcut(KeyCode.F9),"Hidden -> population -> population + status -> hidden.");
   editMode=Config.Bind("General","HUD Edit Mode",false,"Only while enabled: show compact drag hitboxes and allow mouse repositioning.");
   showVersion=Config.Bind("General","Show SPT Version Label",false,"Show/hide the native lower-left SPT version label.");
   popEnabled=Config.Bind("Population","Enabled",true,"Population cluster."); popSize=Config.Bind("Population","Size",10,new ConfigDescription("Size",new AcceptableValueRange<int>(8,20))); popOpacity=Opacity("Population"); popX=X("Population",8); popY=Y("Population",8);
   pmcColor=ColorCfg("Population Colors","PMC",new Color(.55f,.72f,.58f,1)); scavColor=ColorCfg("Population Colors","Scav",new Color(.72f,.48f,.46f,1)); bossColor=ColorCfg("Population Colors","Boss",new Color(.78f,.60f,.38f,1)); reinforcedColor=ColorCfg("Population Colors","Reinforced",new Color(.63f,.51f,.72f,1));
   statusEnabled=Config.Bind("Player Status","Enabled",true,"Hydration, energy and weight."); statusOutside=Config.Bind("Player Status","Show Outside Raid",false,"Keep status cluster available outside raids when profile data is available."); statusSize=Config.Bind("Player Status","Size",10,new ConfigDescription("Size",new AcceptableValueRange<int>(8,20))); statusOpacity=Opacity("Player Status"); statusX=X("Player Status",8); statusY=Y("Player Status",24);
   statusColor=ColorCfg("Player Status Colors","Hydration Energy",new Color(.72f,.76f,.76f,1)); weightOk=ColorCfg("Player Status Colors","Weight OK",new Color(.58f,.75f,.52f,1)); weightHeavy=ColorCfg("Player Status Colors","Weight Heavy",new Color(.78f,.68f,.39f,1)); weightCritical=ColorCfg("Player Status Colors","Weight Critical",new Color(.75f,.42f,.39f,1));
   killEnabled=Config.Bind("Kill Feed","Enabled",false,"Kill feed; live death-event capture is the next implementation block."); killMode=Config.Bind("Kill Feed","Display Mode","Normal",new ConfigDescription("Minimal / Normal / Detailed",new AcceptableValueList<string>("Minimal","Normal","Detailed"))); killSize=Config.Bind("Kill Feed","Size",10,new ConfigDescription("Size",new AcceptableValueRange<int>(8,20))); killOpacity=Opacity("Kill Feed"); killX=X("Kill Feed",1500); killY=Config.Bind("Kill Feed","Position Y",100f,new ConfigDescription("Top position",new AcceptableValueRange<float>(-100,2000))); killNeutral=ColorCfg("Kill Feed Colors","Neutral",new Color(.72f,.74f,.74f,1));
   Logger.LogInfo("SPT Tactical HUD v1.4 loaded");
  }
  ConfigEntry<float> Opacity(string s)=>Config.Bind(s,"Opacity",.55f,new ConfigDescription("0 = invisible, 1 = opaque",new AcceptableValueRange<float>(0,1))); ConfigEntry<float>X(string s,float v)=>Config.Bind(s,"Position X",v,new ConfigDescription("X",new AcceptableValueRange<float>(-400,4000))); ConfigEntry<float>Y(string s,float v)=>Config.Bind(s,"Position Y From Bottom",v,new ConfigDescription("Bottom margin",new AcceptableValueRange<float>(-100,2000))); ConfigEntry<Color>ColorCfg(string s,string k,Color c)=>Config.Bind(s,k,c,"Muted HUD color.");
  void Update(){if(Time.unscaledTime>=nextRefresh){nextRefresh=Time.unscaledTime+.5f;Refresh();}if(Time.unscaledTime>=nextVersionScan){nextVersionScan=Time.unscaledTime+1f;ApplyVersionLabelSetting();}if(!inRaid&&!workAlways.Value&&!statusOutside.Value){mode=0;return;}if(toggleKey.Value.IsDown())mode=(mode+1)%3;}
  void OnGUI(){EnsureStyles();bool debug=workAlways.Value,e=editMode.Value;if((inRaid||debug)&&(mode>=1||e)&&popEnabled.Value)DrawPopulation(PopRect());if((inRaid||debug||statusOutside.Value)&&(mode>=2||e)&&statusEnabled.Value)DrawStatus(StatusRect());if((inRaid||debug)&&killEnabled.Value&&e)DrawPlain(3,KillRect(),KillPreview(),killSize.Value,killOpacity.Value,killNeutral.Value);}
  Rect PopRect()=>new Rect(popX.Value,Screen.height-popY.Value-(popSize.Value+6),Mathf.Max(100,popSize.Value*12),popSize.Value+6); Rect StatusRect()=>new Rect(statusX.Value,Screen.height-statusY.Value-(statusSize.Value+6),Mathf.Max(120,statusSize.Value*15),statusSize.Value+6); Rect KillRect()=>new Rect(killX.Value,killY.Value,killMode.Value=="Minimal"?125:killMode.Value=="Detailed"?210:175,killSize.Value+7);
  void EnsureStyles(){if(text==null)text=new GUIStyle(GUI.skin.label){fontStyle=FontStyle.Normal,padding=new RectOffset(),margin=new RectOffset()};if(shadow==null)shadow=new GUIStyle(text);if(edit==null)edit=new GUIStyle(GUI.skin.box){fontSize=8,alignment=TextAnchor.MiddleCenter};}
  void Prep(int size,float opacity,Color c){text.fontSize=shadow.fontSize=size;c.a*=opacity;text.normal.textColor=c;shadow.normal.textColor=new Color(0,0,0,opacity<=0?0:Mathf.Min(1,opacity+.22f));}
  float Label(Rect r,string s,float x,int size,float opacity,Color c){Prep(size,opacity,c);var content=new GUIContent(s);float w=text.CalcSize(content).x;GUI.Label(new Rect(r.x+x+1,r.y+1,w+3,r.height),s,shadow);GUI.Label(new Rect(r.x+x,r.y,w+3,r.height),s,text);return x+w+2;}
  void DrawPopulation(Rect r){if(editMode.Value){GUI.Box(r,"");HandleDrag(1,r);}float x=0;x=Label(r,"P "+pmc,x,popSize.Value,popOpacity.Value,pmcColor.Value);x=Label(r,"S "+scav,x,popSize.Value,popOpacity.Value,scavColor.Value);x=Label(r,"B "+boss,x,popSize.Value,popOpacity.Value,bossColor.Value);Label(r,"R "+reinforced,x,popSize.Value,popOpacity.Value,reinforcedColor.Value);}
  void DrawStatus(Rect r){if(editMode.Value){GUI.Box(r,"");HandleDrag(2,r);}float x=0;x=Label(r,"H "+Mathf.RoundToInt(hydration),x,statusSize.Value,statusOpacity.Value,statusColor.Value);x=Label(r,"E "+Mathf.RoundToInt(energy),x,statusSize.Value,statusOpacity.Value,statusColor.Value);Color wc=maxWeight<=0?weightOk.Value:(weight/maxWeight<.75f?weightOk.Value:weight/maxWeight<.95f?weightHeavy.Value:weightCritical.Value);Label(r,"W "+Mathf.RoundToInt(weight)+"/"+Mathf.RoundToInt(maxWeight),x,statusSize.Value,statusOpacity.Value,wc);}
  void DrawPlain(int id,Rect r,string s,int size,float opacity,Color c){if(editMode.Value){GUI.Box(r,"");HandleDrag(id,r);}Label(r,s,0,size,opacity,c);}
  void HandleDrag(int id,Rect r){Event e=Event.current;if(e.type==EventType.MouseDown&&e.button==0&&r.Contains(e.mousePosition)){dragCluster=id;dragOffset=e.mousePosition-new Vector2(r.x,r.y);e.Use();}if(e.type==EventType.MouseDrag&&dragCluster==id){Vector2 p=e.mousePosition-dragOffset;p.x=Mathf.Clamp(p.x,-r.width+8,Screen.width-8);p.y=Mathf.Clamp(p.y,-r.height+6,Screen.height-6);if(id==1){popX.Value=p.x;popY.Value=Screen.height-p.y-r.height;}else if(id==2){statusX.Value=p.x;statusY.Value=Screen.height-p.y-r.height;}else{killX.Value=p.x;killY.Value=p.y;}e.Use();}if(e.type==EventType.MouseUp&&dragCluster==id){dragCluster=0;Config.Save();e.Use();}}
  string KillPreview()=>killMode.Value=="Minimal"?"Scav [AK] PMC":"Scav [AK] PMC [HEAD] 187m";
  void ApplyVersionLabelSetting(){try{foreach(var mb in Resources.FindObjectsOfTypeAll<MonoBehaviour>()){if(mb==null)continue;string tn=mb.GetType().Name;if(tn.IndexOf("LocalizedText",StringComparison.OrdinalIgnoreCase)<0&&tn.IndexOf("AlphaLabel",StringComparison.OrdinalIgnoreCase)<0)continue;string value=ReadText(mb);if(string.IsNullOrEmpty(value)||value.IndexOf("SPT",StringComparison.OrdinalIgnoreCase)<0)continue;var go=mb.gameObject;if(go!=null&&go.activeSelf==showVersion.Value)continue;if(go!=null)go.SetActive(showVersion.Value);}}catch(Exception ex){Logger.LogDebug("Version label scan: "+ex.Message);}}
  string ReadText(object o){foreach(string n in new[]{"text","Text","LabelText","_text"}){object v=ReadMember(o,n);if(v is string)return(string)v;}return null;}
  void Refresh(){try{object world=GetWorld();if(world==null){Outside();return;}IEnumerable ps=GetPlayers(world);if(ps==null){Outside();return;}inRaid=true;int p=0,s=0,b=0,r=0;object local=null;foreach(object pl in ps){if(pl==null)continue;if(IsTrue(ReadMember(pl,"IsYourPlayer"))){local=pl;continue;}if(!IsAlive(pl))continue;string role=Role(pl),side=Side(pl);if(IsBoss(role))b++;else if(IsReinforced(role))r++;else if(IsPmc(side))p++;else if(IsScav(side))s++;}pmc=p;scav=s;boss=b;reinforced=r;RefreshStatus(local);}catch(Exception ex){Logger.LogWarning("HUD refresh: "+ex.Message);}}
  void RefreshStatus(object pl){if(pl==null)return;object hc=ReadMember(pl,"HealthController");hydration=ReadFloatDeep(hc,"Hydration","Current")??ReadFloatDeep(hc,"Hydration","Value")??hydration;energy=ReadFloatDeep(hc,"Energy","Current")??ReadFloatDeep(hc,"Energy","Value")??energy;object ph=ReadMember(pl,"Physical");weight=ReadFloat(ReadMember(ph,"CurrentWeight"))??ReadFloat(ReadMember(pl,"Weight"))??weight;maxWeight=ReadFloat(ReadMember(ph,"MaxWeight"))??ReadFloat(ReadMember(ph,"BaseWeightLimit"))??maxWeight;}
  void Outside(){inRaid=false;pmc=scav=boss=reinforced=0;if(!workAlways.Value&&!statusOutside.Value)mode=0;}
  object GetWorld(){if(worldType==null)worldType=FindType("EFT.GameWorld")??FindTypeByName("GameWorld");if(worldType==null)return null;if(singletonType==null)singletonType=FindType("Comfort.Common.Singleton`1");if(singletonType==null)return null;if(singletonInstance==null)singletonInstance=singletonType.MakeGenericType(worldType).GetProperty("Instance",BindingFlags.Public|BindingFlags.Static);return singletonInstance?.GetValue(null,null);} IEnumerable GetPlayers(object w){if(playersMember==null){Type t=w.GetType();playersMember=(MemberInfo)t.GetProperty("RegisteredPlayers",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)??t.GetProperty("AllPlayers",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)??(MemberInfo)t.GetField("RegisteredPlayers",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);}object v=playersMember is PropertyInfo pi?pi.GetValue(w,null):(playersMember as FieldInfo)?.GetValue(w);return v as IEnumerable;}
  static bool IsAlive(object p){object h=ReadMember(p,"HealthController"),a=h!=null?ReadMember(h,"IsAlive"):ReadMember(p,"IsAlive");return !(a is bool)||(bool)a;} static string Side(object p){object pr=ReadMember(p,"Profile"),i=ReadMember(pr,"Info");return(ReadMember(i,"Side")??ReadMember(pr,"Side"))?.ToString();} static string Role(object p){object pr=ReadMember(p,"Profile"),i=ReadMember(pr,"Info"),s=ReadMember(i,"Settings")??ReadMember(pr,"Settings");return(ReadMember(s,"Role")??ReadMember(i,"Role"))?.ToString();} static bool IsPmc(string s)=>s!=null&&(s.IndexOf("USEC",StringComparison.OrdinalIgnoreCase)>=0||s.IndexOf("BEAR",StringComparison.OrdinalIgnoreCase)>=0); static bool IsScav(string s)=>s!=null&&(s.IndexOf("Savage",StringComparison.OrdinalIgnoreCase)>=0||s.IndexOf("Scav",StringComparison.OrdinalIgnoreCase)>=0); static bool IsBoss(string r)=>!string.IsNullOrEmpty(r)&&r.IndexOf("boss",StringComparison.OrdinalIgnoreCase)>=0; static bool IsReinforced(string role){if(string.IsNullOrEmpty(role))return false;string r=role.ToLowerInvariant();return r.Contains("follower")||r.Contains("pmcbot")||r.Contains("exusec")||r.Contains("raider")||r.Contains("rogue")||r.Contains("sectant")||r.Contains("arena")||r.Contains("assaultgroup");}
  static bool IsTrue(object v)=>v is bool&&(bool)v; static float? ReadFloat(object v){if(v==null)return null;try{return Convert.ToSingle(v);}catch{return null;}} static float? ReadFloatDeep(object o,string a,string b){object x=ReadMember(o,a);return ReadFloat(ReadMember(x,b))??ReadFloat(x);} static object ReadMember(object o,string n){if(o==null)return null;Type t=o.GetType();try{var p=t.GetProperty(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);if(p!=null)return p.GetValue(o,null);}catch{}try{var f=t.GetField(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);if(f!=null)return f.GetValue(o);}catch{}return null;} static Type FindType(string n){foreach(Assembly a in AppDomain.CurrentDomain.GetAssemblies())try{Type t=a.GetType(n,false);if(t!=null)return t;}catch{}return null;} static Type FindTypeByName(string n){foreach(Assembly a in AppDomain.CurrentDomain.GetAssemblies()){try{Type t=a.GetTypes().FirstOrDefault(x=>x.Name==n);if(t!=null)return t;}catch(ReflectionTypeLoadException e){Type t=e.Types?.FirstOrDefault(x=>x!=null&&x.Name==n);if(t!=null)return t;}catch{}}return null;}
 }
}
