using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using BepInEx;
using BepInEx.Configuration;
using UnityEngine;
namespace SPTPopCounter{
[BepInPlugin("com.admiralam.spt.tacticalhud","SPT Tactical HUD","1.5.0")]
public sealed class Plugin:BaseUnityPlugin{
 ConfigEntry<bool> workAlways,editMode,popEnabled,statusEnabled,statusOutside,killEnabled,showVersion; ConfigEntry<KeyboardShortcut> toggleKey; ConfigEntry<int> popSize,statusSize,killSize,killMax; ConfigEntry<string> killMode; ConfigEntry<float> popOpacity,statusOpacity,killOpacity,popX,popY,statusX,statusY,killX,killY,killLifetime;
 ConfigEntry<Color> pmcColor,scavColor,bossColor,reinforcedColor,statusColor,weightOk,weightHeavy,weightCritical,killNeutral; float nextRefresh,nextVersionScan;int mode,pmc,scav,boss,reinforced;bool inRaid;float hydration,energy,weight,maxWeight;GUIStyle text,shadow;Type worldType,singletonType;PropertyInfo singletonInstance;MemberInfo playersMember;Vector2 dragOffset;int dragCluster;readonly Dictionary<string,Tracked> tracked=new Dictionary<string,Tracked>();readonly List<KillLine> kills=new List<KillLine>();
 class Tracked{public object Player;public bool Alive;public Vector3 Pos;public string Kind;public string Weapon;} class KillLine{public string Killer,Victim,Weapon,Hit;public float Distance,Created;}
 void Awake(){workAlways=Config.Bind("General","Work Always",false,"Debug override");toggleKey=Config.Bind("General","Toggle Key",new KeyboardShortcut(KeyCode.F9),"Hidden -> population -> population + status -> hidden");editMode=Config.Bind("General","HUD Edit Mode",false,"Enable compact drag hitboxes");showVersion=Config.Bind("General","Show SPT Version Label",false,"Show/hide native SPT version label");popEnabled=Config.Bind("Population","Enabled",true,"Population");popSize=Size("Population");popOpacity=Opacity("Population");popX=X("Population",8);popY=BottomY("Population",8);pmcColor=C("Population Colors","PMC",.55f,.72f,.58f);scavColor=C("Population Colors","Scav",.72f,.48f,.46f);bossColor=C("Population Colors","Boss",.78f,.60f,.38f);reinforcedColor=C("Population Colors","Reinforced",.63f,.51f,.72f);statusEnabled=Config.Bind("Player Status","Enabled",true,"Status");statusOutside=Config.Bind("Player Status","Show Outside Raid",false,"Show outside raid if data exists");statusSize=Size("Player Status");statusOpacity=Opacity("Player Status");statusX=X("Player Status",8);statusY=BottomY("Player Status",24);statusColor=C("Player Status Colors","Hydration Energy",.72f,.76f,.76f);weightOk=C("Player Status Colors","Weight OK",.58f,.75f,.52f);weightHeavy=C("Player Status Colors","Weight Heavy",.78f,.68f,.39f);weightCritical=C("Player Status Colors","Weight Critical",.75f,.42f,.39f);killEnabled=Config.Bind("Kill Feed","Enabled",true,"Runtime kill feed");killMode=Config.Bind("Kill Feed","Display Mode","Normal",new ConfigDescription("Minimal / Normal / Detailed",new AcceptableValueList<string>("Minimal","Normal","Detailed")));killSize=Size("Kill Feed");killOpacity=Opacity("Kill Feed");killX=X("Kill Feed",1500);killY=Config.Bind("Kill Feed","Position Y",100f,new ConfigDescription("Top Y",new AcceptableValueRange<float>(-100,2000)));killLifetime=Config.Bind("Kill Feed","Lifetime",6f,new ConfigDescription("Seconds before fade",new AcceptableValueRange<float>(2,15)));killMax=Config.Bind("Kill Feed","Max Entries",3,new ConfigDescription("Visible lines",new AcceptableValueRange<int>(1,6)));killNeutral=C("Kill Feed Colors","Neutral",.72f,.74f,.74f);Logger.LogInfo("SPT Tactical HUD v1.5 loaded");}
 ConfigEntry<int>Size(string s)=>Config.Bind(s,"Size",10,new ConfigDescription("Size",new AcceptableValueRange<int>(8,20)));ConfigEntry<float>Opacity(string s)=>Config.Bind(s,"Opacity",.55f,new ConfigDescription("0 invisible / 1 opaque",new AcceptableValueRange<float>(0,1)));ConfigEntry<float>X(string s,float v)=>Config.Bind(s,"Position X",v,new ConfigDescription("X",new AcceptableValueRange<float>(-400,4000)));ConfigEntry<float>BottomY(string s,float v)=>Config.Bind(s,"Position Y From Bottom",v,new ConfigDescription("Bottom",new AcceptableValueRange<float>(-100,2000)));ConfigEntry<Color>C(string s,string k,float r,float g,float b)=>Config.Bind(s,k,new Color(r,g,b,1),"Muted color");
 void Update(){if(Time.unscaledTime>=nextRefresh){nextRefresh=Time.unscaledTime+.25f;Refresh();}if(Time.unscaledTime>=nextVersionScan){nextVersionScan=Time.unscaledTime+1;ApplyVersion();}kills.RemoveAll(k=>Time.unscaledTime-k.Created>killLifetime.Value);if(!inRaid&&!workAlways.Value&&!statusOutside.Value){mode=0;return;}if(toggleKey.Value.IsDown())mode=(mode+1)%3;}
 void OnGUI(){Ensure();bool d=workAlways.Value,e=editMode.Value;if((inRaid||d)&&(mode>=1||e)&&popEnabled.Value)DrawPop(PopRect());if((inRaid||d||statusOutside.Value)&&(mode>=2||e)&&statusEnabled.Value)DrawStatus(StatusRect());if((inRaid||d)&&killEnabled.Value)DrawKills(KillRect(),e);}
 Rect PopRect()=>new Rect(popX.Value,Screen.height-popY.Value-(popSize.Value+6),Mathf.Max(88,popSize.Value*11),popSize.Value+6);Rect StatusRect()=>new Rect(statusX.Value,Screen.height-statusY.Value-(statusSize.Value+6),Mathf.Max(110,statusSize.Value*14),statusSize.Value+6);Rect KillRect()=>new Rect(killX.Value,killY.Value,killMode.Value=="Minimal"?135:205,(killSize.Value+4)*Mathf.Max(1,killMax.Value));void Ensure(){if(text==null)text=new GUIStyle(GUI.skin.label){fontStyle=FontStyle.Normal,padding=new RectOffset(),margin=new RectOffset()};if(shadow==null)shadow=new GUIStyle(text);}
 float L(Rect r,string s,float x,float y,int sz,float op,Color c){text.fontSize=shadow.fontSize=sz;c.a*=op;text.normal.textColor=c;shadow.normal.textColor=new Color(0,0,0,op<=0?0:Mathf.Min(1,op+.22f));float w=text.CalcSize(new GUIContent(s)).x;GUI.Label(new Rect(r.x+x+1,r.y+y+1,w+3,sz+5),s,shadow);GUI.Label(new Rect(r.x+x,r.y+y,w+3,sz+5),s,text);return x+w+2;}
 void BoxDrag(int id,Rect r){if(!editMode.Value)return;GUI.Box(r,"");Event e=Event.current;if(e.type==EventType.MouseDown&&e.button==0&&r.Contains(e.mousePosition)){dragCluster=id;dragOffset=e.mousePosition-new Vector2(r.x,r.y);e.Use();}if(e.type==EventType.MouseDrag&&dragCluster==id){Vector2 p=e.mousePosition-dragOffset;p.x=Mathf.Clamp(p.x,-r.width+8,Screen.width-8);p.y=Mathf.Clamp(p.y,-r.height+6,Screen.height-6);if(id==1){popX.Value=p.x;popY.Value=Screen.height-p.y-r.height;}else if(id==2){statusX.Value=p.x;statusY.Value=Screen.height-p.y-r.height;}else{killX.Value=p.x;killY.Value=p.y;}e.Use();}if(e.type==EventType.MouseUp&&dragCluster==id){dragCluster=0;Config.Save();e.Use();}}
 void DrawPop(Rect r){BoxDrag(1,r);float x=0;x=L(r,"◆"+pmc,x,0,popSize.Value,popOpacity.Value,pmcColor.Value);x=L(r,"●"+scav,x,0,popSize.Value,popOpacity.Value,scavColor.Value);x=L(r,"★"+boss,x,0,popSize.Value,popOpacity.Value,bossColor.Value);L(r,"▲"+reinforced,x,0,popSize.Value,popOpacity.Value,reinforcedColor.Value);}void DrawStatus(Rect r){BoxDrag(2,r);float x=0;x=L(r,"◉"+Mathf.RoundToInt(hydration),x,0,statusSize.Value,statusOpacity.Value,statusColor.Value);x=L(r,"ϟ"+Mathf.RoundToInt(energy),x,0,statusSize.Value,statusOpacity.Value,statusColor.Value);Color wc=maxWeight<=0?weightOk.Value:(weight/maxWeight<.75f?weightOk.Value:weight/maxWeight<.95f?weightHeavy.Value:weightCritical.Value);L(r,"▰"+Mathf.RoundToInt(weight)+"/"+Mathf.RoundToInt(maxWeight),x,0,statusSize.Value,statusOpacity.Value,wc);}
 void DrawKills(Rect r,bool editing){BoxDrag(3,r);if(kills.Count==0){if(editing)L(r,"Scav  [AK]  PMC  ◎  187m",0,0,killSize.Value,killOpacity.Value,killNeutral.Value);return;}int start=Math.Max(0,kills.Count-killMax.Value),row=0;for(int i=kills.Count-1;i>=start;i--){KillLine k=kills[i];float age=Time.unscaledTime-k.Created,fade=Mathf.Clamp01((killLifetime.Value-age)/Mathf.Min(2f,killLifetime.Value));string s=killMode.Value=="Minimal"?$"{k.Killer}  [{k.Weapon}]  {k.Victim}":$"{k.Killer}  [{k.Weapon}]  {k.Victim}  {HitIcon(k.Hit)}  {Mathf.RoundToInt(k.Distance)}m";L(r,s,0,row*(killSize.Value+4),killSize.Value,killOpacity.Value*fade,killNeutral.Value);row++;}}
 string HitIcon(string h){h=(h??"").ToLowerInvariant();if(h.Contains("head"))return "◎";if(h.Contains("arm"))return "⌁";if(h.Contains("leg"))return "⌞";if(h.Contains("stomach"))return "◇";return "▣";}
 void Refresh(){try{object w=GetWorld();if(w==null){Outside();return;}IEnumerable ps=GetPlayers(w);if(ps==null){Outside();return;}inRaid=true;int p=0,s=0,b=0,r=0;object local=null;var seen=new HashSet<string>();foreach(object pl in ps){if(pl==null)continue;string id=PlayerId(pl);if(string.IsNullOrEmpty(id))id=pl.GetHashCode().ToString();seen.Add(id);bool alive=IsAlive(pl);string kind=Kind(pl);Vector3 pos=Position(pl);if(IsTrue(ReadMember(pl,"IsYourPlayer")))local=pl;else if(alive){if(kind=="Boss")b++;else if(kind=="Raider")r++;else if(kind=="PMC")p++;else s++;}Tracked old;if(tracked.TryGetValue(id,out old)&&old.Alive&&!alive)CaptureDeath(pl,old,ps);tracked[id]=new Tracked{Player=pl,Alive=alive,Pos=pos,Kind=kind,Weapon=Weapon(pl)};}foreach(string id in tracked.Keys.Where(x=>!seen.Contains(x)).ToList())tracked.Remove(id);pmc=p;scav=s;boss=b;reinforced=r;RefreshStatus(local);}catch(Exception ex){Logger.LogWarning("HUD refresh: "+ex.Message);}}
 void CaptureDeath(object victim,Tracked old,IEnumerable players){object hc=ReadMember(victim,"HealthController");object info=ReadMember(hc,"LastDamageInfo")??ReadMember(victim,"LastDamageInfo")??ReadMember(hc,"DamageInfo");object attacker=ReadMember(info,"Player")??ReadMember(info,"Attacker")??ReadMember(info,"SourcePlayer");string hit=(ReadMember(info,"BodyPart")??ReadMember(info,"HitBodyPart")??ReadMember(info,"BodyPartType"))?.ToString();float dist=0;string killer="Unknown",weapon="?";if(attacker!=null){killer=Kind(attacker);weapon=Weapon(attacker);dist=Vector3.Distance(Position(attacker),old.Pos);}else{object best=null;float bestD=9999;foreach(object p in players){if(p==null||ReferenceEquals(p,victim)||!IsAlive(p))continue;float d=Vector3.Distance(Position(p),old.Pos);if(d<bestD){bestD=d;best=p;}}if(best!=null&&bestD<150){killer=Kind(best);weapon=Weapon(best);dist=bestD;}}kills.Add(new KillLine{Killer=killer,Victim=old.Kind,Weapon=weapon,Hit=hit,Distance=dist,Created=Time.unscaledTime});}
 string Kind(object p){string role=Role(p),side=Side(p);if(IsBoss(role))return"Boss";if(IsReinforced(role))return"Raider";if(IsPmc(side))return"PMC";return"Scav";}string Weapon(object p){object hands=ReadMember(p,"HandsController"),item=ReadMember(hands,"Item");object tpl=ReadMember(item,"Template");string n=(ReadMember(tpl,"ShortName")??ReadMember(tpl,"Name")??ReadMember(item,"ShortName"))?.ToString();return string.IsNullOrEmpty(n)?"?":n;}
 Vector3 Position(object p){try{object tr=ReadMember(p,"Transform")??ReadMember(p,"transform");object v=ReadMember(tr,"position");if(v is Vector3)return(Vector3)v;}catch{}return Vector3.zero;}string PlayerId(object p){object pr=ReadMember(p,"Profile");return(ReadMember(pr,"Id")??ReadMember(pr,"ProfileId")??ReadMember(p,"ProfileId"))?.ToString();}
 void RefreshStatus(object pl){if(pl==null)return;object hc=ReadMember(pl,"HealthController");hydration=ReadFloatDeep(hc,"Hydration","Current")??ReadFloatDeep(hc,"Hydration","Value")??hydration;energy=ReadFloatDeep(hc,"Energy","Current")??ReadFloatDeep(hc,"Energy","Value")??energy;object ph=ReadMember(pl,"Physical");weight=ReadFloat(ReadMember(ph,"CurrentWeight"))??ReadFloat(ReadMember(pl,"Weight"))??weight;maxWeight=ReadFloat(ReadMember(ph,"MaxWeight"))??ReadFloat(ReadMember(ph,"BaseWeightLimit"))??maxWeight;}
 void Outside(){inRaid=false;pmc=scav=boss=reinforced=0;tracked.Clear();kills.Clear();if(!workAlways.Value&&!statusOutside.Value)mode=0;}void ApplyVersion(){try{foreach(var mb in Resources.FindObjectsOfTypeAll<MonoBehaviour>()){if(mb==null)continue;string tn=mb.GetType().Name;if(tn.IndexOf("LocalizedText",StringComparison.OrdinalIgnoreCase)<0&&tn.IndexOf("AlphaLabel",StringComparison.OrdinalIgnoreCase)<0)continue;string v=ReadText(mb);if(string.IsNullOrEmpty(v)||v.IndexOf("SPT",StringComparison.OrdinalIgnoreCase)<0)continue;if(mb.gameObject!=null&&mb.gameObject.activeSelf!=showVersion.Value)mb.gameObject.SetActive(showVersion.Value);}}catch{}}string ReadText(object o){foreach(string n in new[]{"text","Text","LabelText","_text"}){object v=ReadMember(o,n);if(v is string)return(string)v;}return null;}
 object GetWorld(){if(worldType==null)worldType=FindType("EFT.GameWorld")??FindTypeByName("GameWorld");if(worldType==null)return null;if(singletonType==null)singletonType=FindType("Comfort.Common.Singleton`1");if(singletonType==null)return null;if(singletonInstance==null)singletonInstance=singletonType.MakeGenericType(worldType).GetProperty("Instance",BindingFlags.Public|BindingFlags.Static);return singletonInstance?.GetValue(null,null);}IEnumerable GetPlayers(object w){if(playersMember==null){Type t=w.GetType();playersMember=(MemberInfo)t.GetProperty("RegisteredPlayers",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)??t.GetProperty("AllPlayers",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)??(MemberInfo)t.GetField("RegisteredPlayers",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);}object v=playersMember is PropertyInfo pi?pi.GetValue(w,null):(playersMember as FieldInfo)?.GetValue(w);return v as IEnumerable;}
 static bool IsAlive(object p){object h=ReadMember(p,"HealthController"),a=h!=null?ReadMember(h,"IsAlive"):ReadMember(p,"IsAlive");return!(a is bool)||(bool)a;}static string Side(object p){object pr=ReadMember(p,"Profile"),i=ReadMember(pr,"Info");return(ReadMember(i,"Side")??ReadMember(pr,"Side"))?.ToString();}static string Role(object p){object pr=ReadMember(p,"Profile"),i=ReadMember(pr,"Info"),s=ReadMember(i,"Settings")??ReadMember(pr,"Settings");return(ReadMember(s,"Role")??ReadMember(i,"Role"))?.ToString();}static bool IsPmc(string s)=>s!=null&&(s.IndexOf("USEC",StringComparison.OrdinalIgnoreCase)>=0||s.IndexOf("BEAR",StringComparison.OrdinalIgnoreCase)>=0);static bool IsBoss(string r)=>!string.IsNullOrEmpty(r)&&r.IndexOf("boss",StringComparison.OrdinalIgnoreCase)>=0;static bool IsReinforced(string role){if(string.IsNullOrEmpty(role))return false;string r=role.ToLowerInvariant();return r.Contains("follower")||r.Contains("pmcbot")||r.Contains("exusec")||r.Contains("raider")||r.Contains("rogue")||r.Contains("sectant")||r.Contains("arena")||r.Contains("assaultgroup");}
 static bool IsTrue(object v)=>v is bool&&(bool)v;static float?ReadFloat(object v){if(v==null)return null;try{return Convert.ToSingle(v);}catch{return null;}}static float?ReadFloatDeep(object o,string a,string b){object x=ReadMember(o,a);return ReadFloat(ReadMember(x,b))??ReadFloat(x);}static object ReadMember(object o,string n){if(o==null)return null;Type t=o.GetType();try{var p=t.GetProperty(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);if(p!=null)return p.GetValue(o,null);}catch{}try{var f=t.GetField(n,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);if(f!=null)return f.GetValue(o);}catch{}return null;}static Type FindType(string n){foreach(Assembly a in AppDomain.CurrentDomain.GetAssemblies())try{Type t=a.GetType(n,false);if(t!=null)return t;}catch{}return null;}static Type FindTypeByName(string n){foreach(Assembly a in AppDomain.CurrentDomain.GetAssemblies()){try{Type t=a.GetTypes().FirstOrDefault(x=>x.Name==n);if(t!=null)return t;}catch(ReflectionTypeLoadException e){Type t=e.Types?.FirstOrDefault(x=>x!=null&&x.Name==n);if(t!=null)return t;}catch{}}return null;}
}}
