<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SPT Tactical HUD v1.9.0</AssemblyName>
    <RootNamespace>SPTPopCounter</RootNamespace>
    <Version>1.9.0</Version>
    <AssemblyVersion>1.9.0.0</AssemblyVersion>
    <FileVersion>1.9.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>..\deps\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>..\deps\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
</Project>
