<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SPT-PopCounter</AssemblyName>
    <RootNamespace>SPTPopCounter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Paulov.Bepinex.Framework" Version="2025.7.24.932" />
  </ItemGroup>
</Project>
